lottery/extract/urls.py
from django.urls import path

from . import views

app_name = 'extract'

urlpatterns = [
    path('', views.index, name='index'), 
    path('loto6', views.loto6, name='loto6'), 
    path('loto7', views.loto7, name='loto7'), 
    path('miniloto', views.miniloto, name='miniloto'), 
]

lottery/lottery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('extract/', include('extract.urls'), name='extract')
    path('', include('extract.urls'), name='extract')
]

lottery/extract/models.py
from django.db import models

# Create your models here.

lottery/extract/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
import json
import requests
from bs4 import BeautifulSoup
import itertools
  
# ある一回分の結果が, ユーザが入力したすべての組み合わせについて含むかどうか検証(全部含まない時にだけ0を返す)
def is_matched(_target_combinations, _base_data):
    for target_combination in _target_combinations:
        if set(target_combination) < set(_base_data):
            return 1
    return 0

# 回数をkey, 6個の当選番号と1個のボーナス数字の値の配列をvalueにした辞書を返す関数(中は全部str型, 仕切り用の行も含まれている)
def scrape_loto6():
    # 初期設定
    scrape_url = 'http://sougaku.com/loto6/data/list1/'
    html_content = requests.get(scrape_url).content
    soup = BeautifulSoup(html_content, 'html.parser')
    population_data = soup.find('table', class_='bun_box1')

    # 過去の全結果を配列に格納(要素の例: ['第3回', '1', '5', '15', '31', '36', '38', '13', 'C', '4：2', '126', '5：2', '139', '詳細表示'])
    trs_list = []
    for tr in population_data.find_all('tr'):
        tr_list = []
        for td in tr:
            text = td.text.replace('\n','').replace('\t','')
            if text != '':
                tr_list.append(text)
        trs_list.append(tr_list)

    # 辞書の作成
    results = {}
    for tr in trs_list:
        results[tr[0]] = [tr[i] for i in range(1, 8, 1)]

    return results

def scrape_loto7():
    # 初期設定
    scrape_url = 'http://sougaku.com/loto7/data/list1/'
    html_content = requests.get(scrape_url).content
    soup = BeautifulSoup(html_content, 'html.parser')
    population_data = soup.find('table', class_='bun_box2')

    # 過去の全結果を配列に格納(要素の例: ['第3回', '1', '5', '15', '31', '36', '38', '13', 'C', '4：2', '126', '5：2', '139', '詳細表示'])
    trs_list = []
    for tr in population_data.find_all('tr'):
        tr_list = []
        for td in tr:
            text = td.text.replace('\n','').replace('\t','')
            if text != '':
                tr_list.append(text)
        # 仕切り行の配列の長さが短くてエラーが出てしまうので, あらかじめ省いておく
        if len(tr_list) > 10:
            trs_list.append(tr_list)

    # 辞書の作成
    results = {}
    for tr in trs_list:
        results[tr[0]] = [tr[i] for i in range(1, 10, 1)]

    return results

def scrape_miniloto():
    # 初期設定
    scrape_url = 'http://sougaku.com/miniloto/data/list1/'
    html_content = requests.get(scrape_url).content
    soup = BeautifulSoup(html_content, 'html.parser')
    population_data = soup.find('table', class_='bun_box2')

    # 過去の全結果を配列に格納(要素の例: ['第3回', '1', '5', '15', '31', '36', '38', '13', 'C', '4：2', '126', '5：2', '139', '詳細表示'])
    trs_list = []
    for tr in population_data.find_all('tr'):
        tr_list = []
        for td in tr:
            text = td.text.replace('\n','').replace('\t','')
            if text != '':
                tr_list.append(text)
        trs_list.append(tr_list)

    # 辞書の作成
    results = {}
    for tr in trs_list:
        results[tr[0]] = [tr[i] for i in range(1, 7, 1)]

    return results

def index(request):
    return HttpResponseRedirect(reverse('extract:loto6'))

def loto6(request):
    if request.method == 'POST':
        # 初期設定(スクレイピングによるデータの取得とPOST内容の確認)
        results_all = scrape_loto6()
        targets = request.POST.getlist('targets')
        include = int(request.POST['include'])
        targets_combinations = list(itertools.combinations(targets, include))

        # ユーザが指定した要素を含む結果のみを格納した配列を作成(各要素はgeneration: 第n回とnumbers: [7個の数字]の辞書)
        results_matched = []
        for key in results_all.keys():
            if is_matched(targets_combinations, results_all[key]):
                results_matched.append({'generation': key, 'numbers': results_all[key]})

        return render(request, 'extract/loto6.html', {
            'chosen': targets, 
            'chosen_json': json.dumps(targets), 
            'include': include, 
            'include_json': json.dumps(include), 
            'results': results_matched
        })
    
    return render(request, 'extract/loto6.html', {
        'chosen': None, 
        'results': None
    })

def loto7(request):
    scrape_loto7()
    if request.method == 'POST':
        # 初期設定(スクレイピングによるデータの取得とPOST内容の確認)
        results_all = scrape_loto7()
        targets = request.POST.getlist('targets')
        include = int(request.POST['include'])
        targets_combinations = list(itertools.combinations(targets, include))

        # ユーザが指定した要素を含む結果のみを格納した配列を作成(各要素はgeneration: 第n回とnumbers: [7個の数字]の辞書)
        results_matched = []
        for key in results_all.keys():
            if is_matched(targets_combinations, results_all[key]):
                results_matched.append({'generation': key, 'numbers': results_all[key]})

        return render(request, 'extract/loto7.html', {
            'chosen': targets, 
            'chosen_json': json.dumps(targets), 
            'include': include, 
            'include_json': json.dumps(include), 
            'results': results_matched
        })
    
    return render(request, 'extract/loto7.html', {
        'chosen': None, 
        'results': None
    })

def miniloto(request):
    scrape_loto7()
    if request.method == 'POST':
        # 初期設定(スクレイピングによるデータの取得とPOST内容の確認)
        results_all = scrape_miniloto()
        targets = request.POST.getlist('targets')
        include = int(request.POST['include'])
        targets_combinations = list(itertools.combinations(targets, include))

        # ユーザが指定した要素を含む結果のみを格納した配列を作成(各要素はgeneration: 第n回とnumbers: [7個の数字]の辞書)
        results_matched = []
        for key in results_all.keys():
            if is_matched(targets_combinations, results_all[key]):
                results_matched.append({'generation': key, 'numbers': results_all[key]})

        return render(request, 'extract/miniloto.html', {
            'chosen': targets, 
            'chosen_json': json.dumps(targets), 
            'include': include, 
            'include_json': json.dumps(include),  
            'results': results_matched
        })
    
    return render(request, 'extract/miniloto.html', {
        'chosen': None, 
        'results': None
    })

lottery/extract/templates/extract/index.html
{% extends 'extract/layout.html' %}
{% load crispy_forms_tags %}

{% block head %}
    <script>

    </script>
{% endblock %}

{% block body %}
    <p>メニューバーから該当する銘柄を選択してください</p>
{% endblock %}

lottery/extract/templates/extract/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <title>宝くじ結果照合サイト</title>
        <meta charset="utf-8">
        {% load bootstrap4 %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
        <script src="{% static 'extract/script.js' %}"></script>
        <link rel="icon" href="{% static 'extract/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'extract/style.css' %}">
        
        {% block head %}
        {% endblock  %}
    </head>
    
    <body>
        <div class="header">
            <h4>〜宝くじ結果照合サイト〜</h4>
            <small>
                <p>いくつかの数を選択して個数を指定すると、その候補の中から指定された数が含まれた当選会が表示されます。</p>
                <p>自分で数字を予想する際などに、是非当サイトを利用ください。</p>
            </small>
            
        </div>

        <div class="menu-bar">
            <div id="for-loto6"><a href="{% url 'extract:loto6' %}">ロト6</a></div>
            <div id="for-loto7"><a href="{% url 'extract:loto7' %}">ロト7</a></div>
            <div id="for-miniloto"><a href="{% url 'extract:miniloto' %}">ミニロト</a></div>
        </div>
        
        <div class="content">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

lottery/extract/templates/extract/loto7.html
{% extends 'extract/layout.html' %}
{% load crispy_forms_tags %}

{% block head %}
    <script>
        const chosens = JSON.parse('{{ chosen_json|safe }}');
        const include = JSON.parse('{{ include_json|safe }}');
        document.addEventListener('DOMContentLoaded', function() {
            chosens.forEach((chosen) => {
                const chosenBox = document.getElementById(chosen);
                chosenBox.checked = true;
            })
            const numberInput = document.getElementById('number-input');
            numberInput.value = include;
            numberInput.max = chosens.length;
        })
    </script>
{% endblock %}

{% block body %}
    <h5><span class="brand">ロト7</span>の照合画面です</h5>
    <p><small>以下のチェックボックスにチェックをつけた数字が当選番号に含まれていた回のデータが抽出されます. </small></p>

    <form action="{% url 'extract:loto7' %}" method="post" class="need-check">
        {% csrf_token %}
        <div>
            <table class="table">
                <tr>
                    <td><input type="checkbox" class="checkbox-input" id="1" name="targets" value="1"> 1</td>
                    <td><input type="checkbox" class="checkbox-input" id="2" name="targets" value="2"> 2</td>
                    <td><input type="checkbox" class="checkbox-input" id="3" name="targets" value="3"> 3</td>
                    <td><input type="checkbox" class="checkbox-input" id="4" name="targets" value="4"> 4</td>
                    <td><input type="checkbox" class="checkbox-input" id="5" name="targets" value="5"> 5</td>
                    <td><input type="checkbox" class="checkbox-input" id="6" name="targets" value="6"> 6</td>
                    <td><input type="checkbox" class="checkbox-input" id="7" name="targets" value="7"> 7</td>
                    <td><input type="checkbox" class="checkbox-input" id="8" name="targets" value="8"> 8</td>
                    <td><input type="checkbox" class="checkbox-input" id="9" name="targets" value="9"> 9</td>
                    <td><input type="checkbox" class="checkbox-input" id="10" name="targets" value="10"> 10</td>
                </tr>
                <tr>
                    <td><input type="checkbox" class="checkbox-input" id="11" name="targets" value="11"> 11</td>
                    <td><input type="checkbox" class="checkbox-input" id="12" name="targets" value="12"> 12</td>
                    <td><input type="checkbox" class="checkbox-input" id="13" name="targets" value="13"> 13</td>
                    <td><input type="checkbox" class="checkbox-input" id="14" name="targets" value="14"> 14</td>
                    <td><input type="checkbox" class="checkbox-input" id="15" name="targets" value="15"> 15</td>
                    <td><input type="checkbox" class="checkbox-input" id="16" name="targets" value="16"> 16</td>
                    <td><input type="checkbox" class="checkbox-input" id="17" name="targets" value="17"> 17</td>
                    <td><input type="checkbox" class="checkbox-input" id="18" name="targets" value="18"> 18</td>
                    <td><input type="checkbox" class="checkbox-input" id="19" name="targets" value="19"> 19</td>
                    <td><input type="checkbox" class="checkbox-input" id="20" name="targets" value="20"> 20</td>
                </tr>
                <tr>
                    <td><input type="checkbox" class="checkbox-input" id="21" name="targets" value="21"> 21</td>
                    <td><input type="checkbox" class="checkbox-input" id="22" name="targets" value="22"> 22</td>
                    <td><input type="checkbox" class="checkbox-input" id="23" name="targets" value="23"> 23</td>
                    <td><input type="checkbox" class="checkbox-input" id="24" name="targets" value="24"> 24</td>
                    <td><input type="checkbox" class="checkbox-input" id="25" name="targets" value="25"> 25</td>
                    <td><input type="checkbox" class="checkbox-input" id="26" name="targets" value="26"> 26</td>
                    <td><input type="checkbox" class="checkbox-input" id="27" name="targets" value="27"> 27</td>
                    <td><input type="checkbox" class="checkbox-input" id="28" name="targets" value="28"> 28</td>
                    <td><input type="checkbox" class="checkbox-input" id="29" name="targets" value="29"> 29</td>
                    <td><input type="checkbox" class="checkbox-input" id="30" name="targets" value="30"> 30</td>
                </tr>
                <tr>
                    <td><input type="checkbox" class="checkbox-input" id="31" name="targets" value="31"> 31</td>
                    <td><input type="checkbox" class="checkbox-input" id="32" name="targets" value="32"> 32</td>
                    <td><input type="checkbox" class="checkbox-input" id="33" name="targets" value="33"> 33</td>
                    <td><input type="checkbox" class="checkbox-input" id="34" name="targets" value="34"> 34</td>
                    <td><input type="checkbox" class="checkbox-input" id="35" name="targets" value="35"> 35</td>
                    <td><input type="checkbox" class="checkbox-input" id="36" name="targets" value="36"> 36</td>
                    <td><input type="checkbox" class="checkbox-input" id="37" name="targets" value="37"> 37</td>
                </tr>
            </table>
            <input type="number" class="number-input form-control form-number" id="number-input" name="include" min="1" max="1" value="1"> 個以上一致したものを抽出する
        </div>

        <input type="submit" value="過去の結果と照合する" class="btn btn-primary" style="margin: 3px;">
    </form>

    <hr>

    {% if results != Nome %}
        <div class="result">
            <p class="caption">照合結果</p>
            <p><small>[{% for number in chosen %} {{ number }},  {% endfor %}]の中から{{ include }}個一致したもの</small></p>
            <table class="my-table table table-bordered border-secondary table-sm table-striped">
                <thead>
                    <tr>
                        <th>回数</th>
                        <th colspan="7">本数字</th>
                        <th colspan="2">ボーナス数字</th>
                    </tr>
                </thead>
                <tbody>
                    {% for result in results %}
                        <tr>
                            <td>{{ result.generation }}</td>

                            {% if result.numbers.0 in chosen %}
                                <td class="matched-number">{{ result.numbers.0 }}</td>
                            {% else %}
                                <td>{{ result.numbers.0 }}</td>
                            {% endif %}

                            {% if result.numbers.1 in chosen %}
                                <td class="matched-number">{{ result.numbers.1 }}</td>
                            {% else %}
                                <td>{{ result.numbers.1 }}</td>
                            {% endif %}

                            {% if result.numbers.2 in chosen %}
                                <td class="matched-number">{{ result.numbers.2 }}</td>
                            {% else %}
                                <td>{{ result.numbers.2 }}</td>
                            {% endif %}

                            {% if result.numbers.3 in chosen %}
                                <td class="matched-number">{{ result.numbers.3 }}</td>
                            {% else %}
                                <td>{{ result.numbers.3 }}</td>
                            {% endif %}

                            {% if result.numbers.4 in chosen %}
                                <td class="matched-number">{{ result.numbers.4 }}</td>
                            {% else %}
                                <td>{{ result.numbers.4 }}</td>
                            {% endif %}

                            {% if result.numbers.5 in chosen %}
                                <td class="matched-number">{{ result.numbers.5 }}</td>
                            {% else %}
                                <td>{{ result.numbers.5 }}</td>
                            {% endif %}

                            {% if result.numbers.6 in chosen %}
                                <td class="matched-number">{{ result.numbers.6 }}</td>
                            {% else %}
                                <td>{{ result.numbers.6 }}</td>
                            {% endif %}

                            {% if result.numbers.7 in chosen %}
                                <td class="matched-number">{{ result.numbers.7 }}</td>
                            {% else %}
                                <td>{{ result.numbers.7 }}</td>
                            {% endif %}

                            {% if result.numbers.8 in chosen %}
                                <td class="matched-number">{{ result.numbers.8 }}</td>
                            {% else %}
                                <td>{{ result.numbers.8 }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}

{% endblock %}

lottery/extract/templates/extract/miniloto.html
{% extends 'extract/layout.html' %}
{% load crispy_forms_tags %}

{% block head %}
    <script>
        const chosens = JSON.parse('{{ chosen_json|safe }}');
        const include = JSON.parse('{{ include_json|safe }}');
        document.addEventListener('DOMContentLoaded', function() {
            chosens.forEach((chosen) => {
                const chosenBox = document.getElementById(chosen);
                chosenBox.checked = true;
            })
            const numberInput = document.getElementById('number-input');
            numberInput.value = include;
            numberInput.max = chosens.length;
        })
    </script>
{% endblock %}

{% block body %}
    <h5><span class="brand">ミニロト</span>の照合画面です</h5>
    <p><small>以下のチェックボックスにチェックをつけた数字が当選番号に含まれていた回のデータが抽出されます. </small></p>

    <form action="{% url 'extract:miniloto' %}" method="post" class="need-check">
        {% csrf_token %}
        <div>
            <table class="table">
                <tr>
                    <td><input type="checkbox" class="checkbox-input" id="1" name="targets" value="1"> 1</td>
                    <td><input type="checkbox" class="checkbox-input" id="2" name="targets" value="2"> 2</td>
                    <td><input type="checkbox" class="checkbox-input" id="3" name="targets" value="3"> 3</td>
                    <td><input type="checkbox" class="checkbox-input" id="4" name="targets" value="4"> 4</td>
                    <td><input type="checkbox" class="checkbox-input" id="5" name="targets" value="5"> 5</td>
                    <td><input type="checkbox" class="checkbox-input" id="6" name="targets" value="6"> 6</td>
                    <td><input type="checkbox" class="checkbox-input" id="7" name="targets" value="7"> 7</td>
                    <td><input type="checkbox" class="checkbox-input" id="8" name="targets" value="8"> 8</td>
                    <td><input type="checkbox" class="checkbox-input" id="9" name="targets" value="9"> 9</td>
                    <td><input type="checkbox" class="checkbox-input" id="10" name="targets" value="10"> 10</td>
                </tr>
                <tr>
                    <td><input type="checkbox" class="checkbox-input" id="11" name="targets" value="11"> 11</td>
                    <td><input type="checkbox" class="checkbox-input" id="12" name="targets" value="12"> 12</td>
                    <td><input type="checkbox" class="checkbox-input" id="13" name="targets" value="13"> 13</td>
                    <td><input type="checkbox" class="checkbox-input" id="14" name="targets" value="14"> 14</td>
                    <td><input type="checkbox" class="checkbox-input" id="15" name="targets" value="15"> 15</td>
                    <td><input type="checkbox" class="checkbox-input" id="16" name="targets" value="16"> 16</td>
                    <td><input type="checkbox" class="checkbox-input" id="17" name="targets" value="17"> 17</td>
                    <td><input type="checkbox" class="checkbox-input" id="18" name="targets" value="18"> 18</td>
                    <td><input type="checkbox" class="checkbox-input" id="19" name="targets" value="19"> 19</td>
                    <td><input type="checkbox" class="checkbox-input" id="20" name="targets" value="20"> 20</td>
                </tr>
                <tr>
                    <td><input type="checkbox" class="checkbox-input" id="21" name="targets" value="21"> 21</td>
                    <td><input type="checkbox" class="checkbox-input" id="22" name="targets" value="22"> 22</td>
                    <td><input type="checkbox" class="checkbox-input" id="23" name="targets" value="23"> 23</td>
                    <td><input type="checkbox" class="checkbox-input" id="24" name="targets" value="24"> 24</td>
                    <td><input type="checkbox" class="checkbox-input" id="25" name="targets" value="25"> 25</td>
                    <td><input type="checkbox" class="checkbox-input" id="26" name="targets" value="26"> 26</td>
                    <td><input type="checkbox" class="checkbox-input" id="27" name="targets" value="27"> 27</td>
                    <td><input type="checkbox" class="checkbox-input" id="28" name="targets" value="28"> 28</td>
                    <td><input type="checkbox" class="checkbox-input" id="29" name="targets" value="29"> 29</td>
                    <td><input type="checkbox" class="checkbox-input" id="30" name="targets" value="30"> 30</td>
                </tr>
                <tr>
                    <td><input type="checkbox" class="checkbox-input" id="31" name="targets" value="31"> 31</td>
                </tr>
            </table>
            <input type="number" class="number-input form-control form-number" id="number-input" name="include" min="1" max="1" value="1"> 個以上一致したものを抽出する
        </div>

        <input type="submit" value="過去の結果と照合する" class="btn btn-primary" style="margin: 3px;">
    </form>

    <hr>

    {% if results != Nome %}
        <div class="result">
            <p class="caption">照合結果</p>
            <p><small>[{% for number in chosen %} {{ number }},  {% endfor %}]の中から{{ include }}個一致したもの</small></p>
            <table class="my-table table table-bordered border-secondary table-sm table-striped">
                <thead>
                    <tr>
                        <th>回数</th>
                        <th colspan="5">本数字</th>
                        <th>ボーナス数字</th>
                    </tr>
                </thead>
                <tbody>
                    {% for result in results %}
                        <tr>
                            <td>{{ result.generation }}</td>

                            {% if result.numbers.0 in chosen %}
                                <td class="matched-number">{{ result.numbers.0 }}</td>
                            {% else %}
                                <td>{{ result.numbers.0 }}</td>
                            {% endif %}

                            {% if result.numbers.1 in chosen %}
                                <td class="matched-number">{{ result.numbers.1 }}</td>
                            {% else %}
                                <td>{{ result.numbers.1 }}</td>
                            {% endif %}

                            {% if result.numbers.2 in chosen %}
                                <td class="matched-number">{{ result.numbers.2 }}</td>
                            {% else %}
                                <td>{{ result.numbers.2 }}</td>
                            {% endif %}

                            {% if result.numbers.3 in chosen %}
                                <td class="matched-number">{{ result.numbers.3 }}</td>
                            {% else %}
                                <td>{{ result.numbers.3 }}</td>
                            {% endif %}

                            {% if result.numbers.4 in chosen %}
                                <td class="matched-number">{{ result.numbers.4 }}</td>
                            {% else %}
                                <td>{{ result.numbers.4 }}</td>
                            {% endif %}

                            {% if result.numbers.5 in chosen %}
                                <td class="matched-number">{{ result.numbers.5 }}</td>
                            {% else %}
                                <td>{{ result.numbers.5 }}</td>
                            {% endif %}

                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}

{% endblock %}